name: megacrn
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=2.135=mkl
  - blas-devel=3.9.0=35_h85df5b5_mkl
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.12.2=haa95532_0
  - cudatoolkit=11.1.1=hb074779_13
  - freetype=2.13.3=h0620614_0
  - intel-openmp=2025.0.0=haa95532_1164
  - jpeg=9b=hb83a4c4_2
  - lerc=4.0.0=h5da7b33_0
  - libblas=3.9.0=35_h5709861_mkl
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.5.2=h52bdfb6_0
  - libhwloc=2.12.1=default_h4379cf1_1003
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - liblapacke=3.9.0=35_h3ae206f_mkl
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libpng=1.6.50=h46444df_0
  - libsqlite=3.51.1=hf5d6505_0
  - libtiff=4.5.0=h8a3f274_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.2.4=h2bbff1b_0
  - libwebp-base=1.2.4=h2bbff1b_1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.15.1=h5d26750_0
  - libxml2-16=2.15.1=h692994f_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=20.1.8=h29ce207_0
  - lz4-c=1.9.4=h2bbff1b_1
  - mkl=2024.2.2=h57928b3_16
  - mkl-devel=2024.2.2=h57928b3_16
  - mkl-include=2024.2.2=h57928b3_16
  - ninja=1.13.1=haa95532_0
  - ninja-base=1.13.1=h512dff2_0
  - numpy=1.20.1=py38h0cc643e_0
  - openssl=3.6.0=h725018a_0
  - pandas=1.2.4=py38h60cbd38_0
  - pillow=9.3.0=py38hdc2b20a_1
  - pip=24.2=py38haa95532_0
  - python=3.8.20=hfaddaf0_2_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.8=8_cp38
  - pytorch=1.9.1=py3.8_cuda11.1_cudnn8_0
  - pytz=2024.2=pyhd8ed1ab_0
  - setuptools=59.8.0=py38haa244fe_1
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.51.0=hda9a48d_0
  - tbb=2021.13.0=hd094cb3_4
  - tk=8.6.13=h2c6b04d_3
  - torchaudio=0.9.1=py38
  - torchvision=0.10.1=py38_cu111
  - typing_extensions=4.11.0=py38haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.44.0=py38haa95532_0
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - zlib=1.3.1=h2466b09_2
  - zstd=1.5.7=h56299aa_0
  - pip:
      - blosc2==2.0.0
      - cython==3.2.3
      - jpholiday==1.0.2
      - msgpack==1.1.1
      - numexpr==2.8.6
      - packaging==25.0
      - py-cpuinfo==9.0.0
      - tables==3.8.0
      - torch-summary==1.4.5
prefix: C:\Users\C Baker\.conda\envs\megacrn
